// AUTO-GENERATED by ffigen — do not edit manually.
// Regenerate with: dart run ffigen --config ffigen.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Auto-generated FFI bindings for the gopost_engine C API.
class GopostEngineBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GopostEngineBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GopostEngineBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  Error engine_create(
    ffi.Pointer<ffi.Pointer<Engine>> engine,
    ffi.Pointer<EngineConfig> config,
  ) {
    return Error.fromValue(_engine_create(engine, config));
  }

  late final _engine_createPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<ffi.Pointer<Engine>>,
        ffi.Pointer<EngineConfig>,
      )
    >
  >('gopost_engine_create');
  late final _engine_create =
      _engine_createPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Pointer<Engine>>,
              ffi.Pointer<EngineConfig>,
            )
          >();

  Error engine_destroy(ffi.Pointer<Engine> engine) {
    return Error.fromValue(_engine_destroy(engine));
  }

  late final _engine_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<Engine>)>>(
        'gopost_engine_destroy',
      );
  late final _engine_destroy =
      _engine_destroyPtr.asFunction<int Function(ffi.Pointer<Engine>)>();

  Error engine_get_version(
    ffi.Pointer<ffi.Uint32> major,
    ffi.Pointer<ffi.Uint32> minor,
    ffi.Pointer<ffi.Uint32> patch,
  ) {
    return Error.fromValue(_engine_get_version(major, minor, patch));
  }

  late final _engine_get_versionPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<ffi.Uint32>,
        ffi.Pointer<ffi.Uint32>,
        ffi.Pointer<ffi.Uint32>,
      )
    >
  >('gopost_engine_get_version');
  late final _engine_get_version =
      _engine_get_versionPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Uint32>,
              ffi.Pointer<ffi.Uint32>,
              ffi.Pointer<ffi.Uint32>,
            )
          >();

  /// Frame pool
  Error frame_acquire(
    ffi.Pointer<Engine> engine,
    ffi.Pointer<ffi.Pointer<Frame>> frame,
    int width,
    int height,
    PixelFormat format,
  ) {
    return Error.fromValue(
      _frame_acquire(engine, frame, width, height, format.value),
    );
  }

  late final _frame_acquirePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Engine>,
        ffi.Pointer<ffi.Pointer<Frame>>,
        ffi.Uint32,
        ffi.Uint32,
        ffi.UnsignedInt,
      )
    >
  >('gopost_frame_acquire');
  late final _frame_acquire =
      _frame_acquirePtr
          .asFunction<
            int Function(
              ffi.Pointer<Engine>,
              ffi.Pointer<ffi.Pointer<Frame>>,
              int,
              int,
              int,
            )
          >();

  Error frame_release(ffi.Pointer<Engine> engine, ffi.Pointer<Frame> frame) {
    return Error.fromValue(_frame_release(engine, frame));
  }

  late final _frame_releasePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Engine>, ffi.Pointer<Frame>)
    >
  >('gopost_frame_release');
  late final _frame_release =
      _frame_releasePtr
          .asFunction<int Function(ffi.Pointer<Engine>, ffi.Pointer<Frame>)>();

  ffi.Pointer<ffi.Char> error_string(Error error) {
    return _error_string(error.value);
  }

  late final _error_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'gopost_error_string',
      );
  late final _error_string =
      _error_stringPtr.asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  Error crypto_create(ffi.Pointer<ffi.Pointer<CryptoContext>> ctx) {
    return Error.fromValue(_crypto_create(ctx));
  }

  late final _crypto_createPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ffi.Pointer<CryptoContext>>)
    >
  >('gopost_crypto_create');
  late final _crypto_create =
      _crypto_createPtr
          .asFunction<int Function(ffi.Pointer<ffi.Pointer<CryptoContext>>)>();

  Error crypto_destroy(ffi.Pointer<CryptoContext> ctx) {
    return Error.fromValue(_crypto_destroy(ctx));
  }

  late final _crypto_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<CryptoContext>)>>(
        'gopost_crypto_destroy',
      );
  late final _crypto_destroy =
      _crypto_destroyPtr.asFunction<int Function(ffi.Pointer<CryptoContext>)>();

  Error crypto_aes_gcm_decrypt(
    ffi.Pointer<CryptoContext> ctx,
    ffi.Pointer<ffi.Uint8> ciphertext,
    int ciphertext_len,
    ffi.Pointer<ffi.Uint8> key,
    int key_len,
    ffi.Pointer<ffi.Uint8> nonce,
    int nonce_len,
    ffi.Pointer<ffi.Uint8> aad,
    int aad_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> plaintext,
    ffi.Pointer<ffi.Size> plaintext_len,
  ) {
    return Error.fromValue(
      _crypto_aes_gcm_decrypt(
        ctx,
        ciphertext,
        ciphertext_len,
        key,
        key_len,
        nonce,
        nonce_len,
        aad,
        aad_len,
        plaintext,
        plaintext_len,
      ),
    );
  }

  late final _crypto_aes_gcm_decryptPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<CryptoContext>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('gopost_crypto_aes_gcm_decrypt');
  late final _crypto_aes_gcm_decrypt =
      _crypto_aes_gcm_decryptPtr
          .asFunction<
            int Function(
              ffi.Pointer<CryptoContext>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.Size>,
            )
          >();

  Error crypto_secure_free(
    ffi.Pointer<CryptoContext> ctx,
    ffi.Pointer<ffi.Uint8> data,
    int data_len,
  ) {
    return Error.fromValue(_crypto_secure_free(ctx, data, data_len));
  }

  late final _crypto_secure_freePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<CryptoContext>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
      )
    >
  >('gopost_crypto_secure_free');
  late final _crypto_secure_free =
      _crypto_secure_freePtr
          .asFunction<
            int Function(
              ffi.Pointer<CryptoContext>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  Error gpu_create_for_platform(ffi.Pointer<ffi.Pointer<GpuContext>> ctx) {
    return Error.fromValue(_gpu_create_for_platform(ctx));
  }

  late final _gpu_create_for_platformPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Pointer<GpuContext>>)>
  >('gopost_gpu_create_for_platform');
  late final _gpu_create_for_platform =
      _gpu_create_for_platformPtr
          .asFunction<int Function(ffi.Pointer<ffi.Pointer<GpuContext>>)>();

  Error gpu_destroy(ffi.Pointer<GpuContext> ctx) {
    return Error.fromValue(_gpu_destroy(ctx));
  }

  late final _gpu_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<GpuContext>)>>(
        'gopost_gpu_destroy',
      );
  late final _gpu_destroy =
      _gpu_destroyPtr.asFunction<int Function(ffi.Pointer<GpuContext>)>();

  GpuBackend gpu_get_backend(ffi.Pointer<GpuContext> ctx) {
    return GpuBackend.fromValue(_gpu_get_backend(ctx));
  }

  late final _gpu_get_backendPtr = _lookup<
    ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<GpuContext>)>
  >('gopost_gpu_get_backend');
  late final _gpu_get_backend =
      _gpu_get_backendPtr.asFunction<int Function(ffi.Pointer<GpuContext>)>();

  Error gpu_create_texture(
    ffi.Pointer<GpuContext> ctx,
    ffi.Pointer<ffi.Pointer<Texture>> texture,
    int width,
    int height,
    PixelFormat format,
  ) {
    return Error.fromValue(
      _gpu_create_texture(ctx, texture, width, height, format.value),
    );
  }

  late final _gpu_create_texturePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<GpuContext>,
        ffi.Pointer<ffi.Pointer<Texture>>,
        ffi.Uint32,
        ffi.Uint32,
        ffi.UnsignedInt,
      )
    >
  >('gopost_gpu_create_texture');
  late final _gpu_create_texture =
      _gpu_create_texturePtr
          .asFunction<
            int Function(
              ffi.Pointer<GpuContext>,
              ffi.Pointer<ffi.Pointer<Texture>>,
              int,
              int,
              int,
            )
          >();

  Error gpu_destroy_texture(
    ffi.Pointer<GpuContext> ctx,
    ffi.Pointer<Texture> texture,
  ) {
    return Error.fromValue(_gpu_destroy_texture(ctx, texture));
  }

  late final _gpu_destroy_texturePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<GpuContext>, ffi.Pointer<Texture>)
    >
  >('gopost_gpu_destroy_texture');
  late final _gpu_destroy_texture =
      _gpu_destroy_texturePtr
          .asFunction<
            int Function(ffi.Pointer<GpuContext>, ffi.Pointer<Texture>)
          >();

  Error gpu_upload_texture(
    ffi.Pointer<GpuContext> ctx,
    ffi.Pointer<Texture> texture,
    ffi.Pointer<ffi.Uint8> data,
    int data_size,
  ) {
    return Error.fromValue(_gpu_upload_texture(ctx, texture, data, data_size));
  }

  late final _gpu_upload_texturePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<GpuContext>,
        ffi.Pointer<Texture>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
      )
    >
  >('gopost_gpu_upload_texture');
  late final _gpu_upload_texture =
      _gpu_upload_texturePtr
          .asFunction<
            int Function(
              ffi.Pointer<GpuContext>,
              ffi.Pointer<Texture>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  Error template_parse(
    ffi.Pointer<Engine> engine,
    ffi.Pointer<ffi.Uint8> data,
    int data_len,
    ffi.Pointer<ffi.Uint8> session_key,
    int key_len,
    ffi.Pointer<ffi.Pointer<Template>> out_template,
  ) {
    return Error.fromValue(
      _template_parse(
        engine,
        data,
        data_len,
        session_key,
        key_len,
        out_template,
      ),
    );
  }

  late final _template_parsePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Engine>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<Template>>,
      )
    >
  >('gopost_template_parse');
  late final _template_parse =
      _template_parsePtr
          .asFunction<
            int Function(
              ffi.Pointer<Engine>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Pointer<Template>>,
            )
          >();

  Error template_get_metadata(
    ffi.Pointer<Template> tpl,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_json,
  ) {
    return Error.fromValue(_template_get_metadata(tpl, out_json));
  }

  late final _template_get_metadataPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Template>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
      )
    >
  >('gopost_template_get_metadata');
  late final _template_get_metadata =
      _template_get_metadataPtr
          .asFunction<
            int Function(
              ffi.Pointer<Template>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  Error template_get_layer_count(
    ffi.Pointer<Template> tpl,
    ffi.Pointer<ffi.Uint32> out_count,
  ) {
    return Error.fromValue(_template_get_layer_count(tpl, out_count));
  }

  late final _template_get_layer_countPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Template>, ffi.Pointer<ffi.Uint32>)
    >
  >('gopost_template_get_layer_count');
  late final _template_get_layer_count =
      _template_get_layer_countPtr
          .asFunction<
            int Function(ffi.Pointer<Template>, ffi.Pointer<ffi.Uint32>)
          >();

  Error template_unload(ffi.Pointer<Engine> engine, ffi.Pointer<Template> tpl) {
    return Error.fromValue(_template_unload(engine, tpl));
  }

  late final _template_unloadPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Engine>, ffi.Pointer<Template>)
    >
  >('gopost_template_unload');
  late final _template_unload =
      _template_unloadPtr
          .asFunction<
            int Function(ffi.Pointer<Engine>, ffi.Pointer<Template>)
          >();

  /// --- Decoder (S5-01) ---
  Error image_probe(
    ffi.Pointer<ffi.Uint8> data,
    int data_len,
    ffi.Pointer<ImageInfo> out_info,
  ) {
    return Error.fromValue(_image_probe(data, data_len, out_info));
  }

  late final _image_probePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Size, ffi.Pointer<ImageInfo>)
    >
  >('gopost_image_probe');
  late final _image_probe =
      _image_probePtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<ImageInfo>)
          >();

  Error image_decode(
    ffi.Pointer<Engine> engine,
    ffi.Pointer<ffi.Uint8> data,
    int data_len,
    ffi.Pointer<ffi.Pointer<Frame>> out_frame,
  ) {
    return Error.fromValue(_image_decode(engine, data, data_len, out_frame));
  }

  late final _image_decodePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Engine>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<Frame>>,
      )
    >
  >('gopost_image_decode');
  late final _image_decode =
      _image_decodePtr
          .asFunction<
            int Function(
              ffi.Pointer<Engine>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Pointer<Frame>>,
            )
          >();

  Error image_decode_file(
    ffi.Pointer<Engine> engine,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Pointer<Frame>> out_frame,
  ) {
    return Error.fromValue(_image_decode_file(engine, path, out_frame));
  }

  late final _image_decode_filePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Engine>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<Frame>>,
      )
    >
  >('gopost_image_decode_file');
  late final _image_decode_file =
      _image_decode_filePtr
          .asFunction<
            int Function(
              ffi.Pointer<Engine>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<Frame>>,
            )
          >();

  Error image_decode_resize(
    ffi.Pointer<Engine> engine,
    ffi.Pointer<ffi.Uint8> data,
    int data_len,
    int max_width,
    int max_height,
    ffi.Pointer<ffi.Pointer<Frame>> out_frame,
  ) {
    return Error.fromValue(
      _image_decode_resize(
        engine,
        data,
        data_len,
        max_width,
        max_height,
        out_frame,
      ),
    );
  }

  late final _image_decode_resizePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Engine>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Int32,
        ffi.Int32,
        ffi.Pointer<ffi.Pointer<Frame>>,
      )
    >
  >('gopost_image_decode_resize');
  late final _image_decode_resize =
      _image_decode_resizePtr
          .asFunction<
            int Function(
              ffi.Pointer<Engine>,
              ffi.Pointer<ffi.Uint8>,
              int,
              int,
              int,
              ffi.Pointer<ffi.Pointer<Frame>>,
            )
          >();

  Error image_encode_jpeg(
    ffi.Pointer<Frame> frame,
    ffi.Pointer<JpegEncodeOpts> opts,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_data,
    ffi.Pointer<ffi.Size> out_size,
  ) {
    return Error.fromValue(_image_encode_jpeg(frame, opts, out_data, out_size));
  }

  late final _image_encode_jpegPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Frame>,
        ffi.Pointer<JpegEncodeOpts>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('gopost_image_encode_jpeg');
  late final _image_encode_jpeg =
      _image_encode_jpegPtr
          .asFunction<
            int Function(
              ffi.Pointer<Frame>,
              ffi.Pointer<JpegEncodeOpts>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.Size>,
            )
          >();

  Error image_encode_png(
    ffi.Pointer<Frame> frame,
    ffi.Pointer<PngEncodeOpts> opts,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_data,
    ffi.Pointer<ffi.Size> out_size,
  ) {
    return Error.fromValue(_image_encode_png(frame, opts, out_data, out_size));
  }

  late final _image_encode_pngPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Frame>,
        ffi.Pointer<PngEncodeOpts>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('gopost_image_encode_png');
  late final _image_encode_png =
      _image_encode_pngPtr
          .asFunction<
            int Function(
              ffi.Pointer<Frame>,
              ffi.Pointer<PngEncodeOpts>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.Size>,
            )
          >();

  Error image_encode_webp(
    ffi.Pointer<Frame> frame,
    ffi.Pointer<WebpEncodeOpts> opts,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_data,
    ffi.Pointer<ffi.Size> out_size,
  ) {
    return Error.fromValue(_image_encode_webp(frame, opts, out_data, out_size));
  }

  late final _image_encode_webpPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Frame>,
        ffi.Pointer<WebpEncodeOpts>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('gopost_image_encode_webp');
  late final _image_encode_webp =
      _image_encode_webpPtr
          .asFunction<
            int Function(
              ffi.Pointer<Frame>,
              ffi.Pointer<WebpEncodeOpts>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.Size>,
            )
          >();

  Error image_encode_to_file(
    ffi.Pointer<Frame> frame,
    ffi.Pointer<ffi.Char> path,
    ImageFormat format,
    int quality,
  ) {
    return Error.fromValue(
      _image_encode_to_file(frame, path, format.value, quality),
    );
  }

  late final _image_encode_to_filePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Frame>,
        ffi.Pointer<ffi.Char>,
        ffi.UnsignedInt,
        ffi.Int32,
      )
    >
  >('gopost_image_encode_to_file');
  late final _image_encode_to_file =
      _image_encode_to_filePtr
          .asFunction<
            int Function(ffi.Pointer<Frame>, ffi.Pointer<ffi.Char>, int, int)
          >();

  void image_encode_free(ffi.Pointer<ffi.Uint8> data) {
    return _image_encode_free(data);
  }

  late final _image_encode_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Uint8>)>>(
        'gopost_image_encode_free',
      );
  late final _image_encode_free =
      _image_encode_freePtr.asFunction<void Function(ffi.Pointer<ffi.Uint8>)>();

  /// --- Canvas lifecycle (S5-03) ---
  Error canvas_create(
    ffi.Pointer<Engine> engine,
    ffi.Pointer<CanvasConfig> config,
    ffi.Pointer<ffi.Pointer<Canvas>> out_canvas,
  ) {
    return Error.fromValue(_canvas_create(engine, config, out_canvas));
  }

  late final _canvas_createPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Engine>,
        ffi.Pointer<CanvasConfig>,
        ffi.Pointer<ffi.Pointer<Canvas>>,
      )
    >
  >('gopost_canvas_create');
  late final _canvas_create =
      _canvas_createPtr
          .asFunction<
            int Function(
              ffi.Pointer<Engine>,
              ffi.Pointer<CanvasConfig>,
              ffi.Pointer<ffi.Pointer<Canvas>>,
            )
          >();

  Error canvas_destroy(ffi.Pointer<Canvas> canvas) {
    return Error.fromValue(_canvas_destroy(canvas));
  }

  late final _canvas_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<Canvas>)>>(
        'gopost_canvas_destroy',
      );
  late final _canvas_destroy =
      _canvas_destroyPtr.asFunction<int Function(ffi.Pointer<Canvas>)>();

  Error canvas_get_size(
    ffi.Pointer<Canvas> canvas,
    ffi.Pointer<ffi.Int32> out_width,
    ffi.Pointer<ffi.Int32> out_height,
    ffi.Pointer<ffi.Float> out_dpi,
  ) {
    return Error.fromValue(
      _canvas_get_size(canvas, out_width, out_height, out_dpi),
    );
  }

  late final _canvas_get_sizePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Pointer<ffi.Int32>,
        ffi.Pointer<ffi.Int32>,
        ffi.Pointer<ffi.Float>,
      )
    >
  >('gopost_canvas_get_size');
  late final _canvas_get_size =
      _canvas_get_sizePtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              ffi.Pointer<ffi.Int32>,
              ffi.Pointer<ffi.Int32>,
              ffi.Pointer<ffi.Float>,
            )
          >();

  Error canvas_resize(ffi.Pointer<Canvas> canvas, int width, int height) {
    return Error.fromValue(_canvas_resize(canvas, width, height));
  }

  late final _canvas_resizePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.Int32)
    >
  >('gopost_canvas_resize');
  late final _canvas_resize =
      _canvas_resizePtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int, int)>();

  /// --- Layer management (S5-03) ---
  Error canvas_add_image_layer(
    ffi.Pointer<Canvas> canvas,
    ffi.Pointer<ffi.Uint8> rgba_pixels,
    int width,
    int height,
    int index,
    ffi.Pointer<ffi.Int32> out_layer_id,
  ) {
    return Error.fromValue(
      _canvas_add_image_layer(
        canvas,
        rgba_pixels,
        width,
        height,
        index,
        out_layer_id,
      ),
    );
  }

  late final _canvas_add_image_layerPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Int32,
        ffi.Int32,
        ffi.Int32,
        ffi.Pointer<ffi.Int32>,
      )
    >
  >('gopost_canvas_add_image_layer');
  late final _canvas_add_image_layer =
      _canvas_add_image_layerPtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              ffi.Pointer<ffi.Uint8>,
              int,
              int,
              int,
              ffi.Pointer<ffi.Int32>,
            )
          >();

  Error canvas_add_solid_layer(
    ffi.Pointer<Canvas> canvas,
    double r,
    double g,
    double b,
    double a,
    int width,
    int height,
    int index,
    ffi.Pointer<ffi.Int32> out_layer_id,
  ) {
    return Error.fromValue(
      _canvas_add_solid_layer(
        canvas,
        r,
        g,
        b,
        a,
        width,
        height,
        index,
        out_layer_id,
      ),
    );
  }

  late final _canvas_add_solid_layerPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Float,
        ffi.Float,
        ffi.Float,
        ffi.Float,
        ffi.Int32,
        ffi.Int32,
        ffi.Int32,
        ffi.Pointer<ffi.Int32>,
      )
    >
  >('gopost_canvas_add_solid_layer');
  late final _canvas_add_solid_layer =
      _canvas_add_solid_layerPtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              double,
              double,
              double,
              double,
              int,
              int,
              int,
              ffi.Pointer<ffi.Int32>,
            )
          >();

  Error canvas_add_group_layer(
    ffi.Pointer<Canvas> canvas,
    ffi.Pointer<ffi.Char> name,
    int index,
    ffi.Pointer<ffi.Int32> out_layer_id,
  ) {
    return Error.fromValue(
      _canvas_add_group_layer(canvas, name, index, out_layer_id),
    );
  }

  late final _canvas_add_group_layerPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Pointer<ffi.Int32>,
      )
    >
  >('gopost_canvas_add_group_layer');
  late final _canvas_add_group_layer =
      _canvas_add_group_layerPtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Int32>,
            )
          >();

  Error canvas_remove_layer(ffi.Pointer<Canvas> canvas, int layer_id) {
    return Error.fromValue(_canvas_remove_layer(canvas, layer_id));
  }

  late final _canvas_remove_layerPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32)>
  >('gopost_canvas_remove_layer');
  late final _canvas_remove_layer =
      _canvas_remove_layerPtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int)>();

  Error canvas_reorder_layer(
    ffi.Pointer<Canvas> canvas,
    int layer_id,
    int new_index,
  ) {
    return Error.fromValue(_canvas_reorder_layer(canvas, layer_id, new_index));
  }

  late final _canvas_reorder_layerPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.Int32)
    >
  >('gopost_canvas_reorder_layer');
  late final _canvas_reorder_layer =
      _canvas_reorder_layerPtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int, int)>();

  Error canvas_duplicate_layer(
    ffi.Pointer<Canvas> canvas,
    int layer_id,
    ffi.Pointer<ffi.Int32> out_new_id,
  ) {
    return Error.fromValue(
      _canvas_duplicate_layer(canvas, layer_id, out_new_id),
    );
  }

  late final _canvas_duplicate_layerPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.Pointer<ffi.Int32>)
    >
  >('gopost_canvas_duplicate_layer');
  late final _canvas_duplicate_layer =
      _canvas_duplicate_layerPtr
          .asFunction<
            int Function(ffi.Pointer<Canvas>, int, ffi.Pointer<ffi.Int32>)
          >();

  /// --- Layer properties (S5-03) ---
  Error layer_set_visible(
    ffi.Pointer<Canvas> canvas,
    int layer_id,
    int visible,
  ) {
    return Error.fromValue(_layer_set_visible(canvas, layer_id, visible));
  }

  late final _layer_set_visiblePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.Int32)
    >
  >('gopost_layer_set_visible');
  late final _layer_set_visible =
      _layer_set_visiblePtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int, int)>();

  Error layer_set_locked(ffi.Pointer<Canvas> canvas, int layer_id, int locked) {
    return Error.fromValue(_layer_set_locked(canvas, layer_id, locked));
  }

  late final _layer_set_lockedPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.Int32)
    >
  >('gopost_layer_set_locked');
  late final _layer_set_locked =
      _layer_set_lockedPtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int, int)>();

  Error layer_set_opacity(
    ffi.Pointer<Canvas> canvas,
    int layer_id,
    double opacity,
  ) {
    return Error.fromValue(_layer_set_opacity(canvas, layer_id, opacity));
  }

  late final _layer_set_opacityPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.Float)
    >
  >('gopost_layer_set_opacity');
  late final _layer_set_opacity =
      _layer_set_opacityPtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int, double)>();

  Error layer_set_blend_mode(
    ffi.Pointer<Canvas> canvas,
    int layer_id,
    BlendMode mode,
  ) {
    return Error.fromValue(_layer_set_blend_mode(canvas, layer_id, mode.value));
  }

  late final _layer_set_blend_modePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.UnsignedInt)
    >
  >('gopost_layer_set_blend_mode');
  late final _layer_set_blend_mode =
      _layer_set_blend_modePtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int, int)>();

  Error layer_set_name(
    ffi.Pointer<Canvas> canvas,
    int layer_id,
    ffi.Pointer<ffi.Char> name,
  ) {
    return Error.fromValue(_layer_set_name(canvas, layer_id, name));
  }

  late final _layer_set_namePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.Pointer<ffi.Char>)
    >
  >('gopost_layer_set_name');
  late final _layer_set_name =
      _layer_set_namePtr
          .asFunction<
            int Function(ffi.Pointer<Canvas>, int, ffi.Pointer<ffi.Char>)
          >();

  Error layer_set_transform(
    ffi.Pointer<Canvas> canvas,
    int layer_id,
    double tx,
    double ty,
    double sx,
    double sy,
    double rotation,
  ) {
    return Error.fromValue(
      _layer_set_transform(canvas, layer_id, tx, ty, sx, sy, rotation),
    );
  }

  late final _layer_set_transformPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Int32,
        ffi.Float,
        ffi.Float,
        ffi.Float,
        ffi.Float,
        ffi.Float,
      )
    >
  >('gopost_layer_set_transform');
  late final _layer_set_transform =
      _layer_set_transformPtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              int,
              double,
              double,
              double,
              double,
              double,
            )
          >();

  Error canvas_get_layer_count(
    ffi.Pointer<Canvas> canvas,
    ffi.Pointer<ffi.Int32> out_count,
  ) {
    return Error.fromValue(_canvas_get_layer_count(canvas, out_count));
  }

  late final _canvas_get_layer_countPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Pointer<ffi.Int32>)
    >
  >('gopost_canvas_get_layer_count');
  late final _canvas_get_layer_count =
      _canvas_get_layer_countPtr
          .asFunction<
            int Function(ffi.Pointer<Canvas>, ffi.Pointer<ffi.Int32>)
          >();

  Error canvas_get_layer_info(
    ffi.Pointer<Canvas> canvas,
    int layer_id,
    ffi.Pointer<LayerInfo> out_info,
  ) {
    return Error.fromValue(_canvas_get_layer_info(canvas, layer_id, out_info));
  }

  late final _canvas_get_layer_infoPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32, ffi.Pointer<LayerInfo>)
    >
  >('gopost_canvas_get_layer_info');
  late final _canvas_get_layer_info =
      _canvas_get_layer_infoPtr
          .asFunction<
            int Function(ffi.Pointer<Canvas>, int, ffi.Pointer<LayerInfo>)
          >();

  /// --- Composition & rendering (S5-04) ---
  Error canvas_render(
    ffi.Pointer<Canvas> canvas,
    ffi.Pointer<ffi.Pointer<Frame>> out_frame,
  ) {
    return Error.fromValue(_canvas_render(canvas, out_frame));
  }

  late final _canvas_renderPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Pointer<ffi.Pointer<Frame>>)
    >
  >('gopost_canvas_render');
  late final _canvas_render =
      _canvas_renderPtr
          .asFunction<
            int Function(ffi.Pointer<Canvas>, ffi.Pointer<ffi.Pointer<Frame>>)
          >();

  Error canvas_render_region(
    ffi.Pointer<Canvas> canvas,
    double x,
    double y,
    double w,
    double h,
    ffi.Pointer<ffi.Pointer<Frame>> out_frame,
  ) {
    return Error.fromValue(
      _canvas_render_region(canvas, x, y, w, h, out_frame),
    );
  }

  late final _canvas_render_regionPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Float,
        ffi.Float,
        ffi.Float,
        ffi.Float,
        ffi.Pointer<ffi.Pointer<Frame>>,
      )
    >
  >('gopost_canvas_render_region');
  late final _canvas_render_region =
      _canvas_render_regionPtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              double,
              double,
              double,
              double,
              ffi.Pointer<ffi.Pointer<Frame>>,
            )
          >();

  Error canvas_invalidate(ffi.Pointer<Canvas> canvas) {
    return Error.fromValue(_canvas_invalidate(canvas));
  }

  late final _canvas_invalidatePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<Canvas>)>>(
        'gopost_canvas_invalidate',
      );
  late final _canvas_invalidate =
      _canvas_invalidatePtr.asFunction<int Function(ffi.Pointer<Canvas>)>();

  Error canvas_invalidate_layer(ffi.Pointer<Canvas> canvas, int layer_id) {
    return Error.fromValue(_canvas_invalidate_layer(canvas, layer_id));
  }

  late final _canvas_invalidate_layerPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32)>
  >('gopost_canvas_invalidate_layer');
  late final _canvas_invalidate_layer =
      _canvas_invalidate_layerPtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int)>();

  /// --- GPU texture output (S5-05) ---
  Error canvas_render_gpu(
    ffi.Pointer<Canvas> canvas,
    ffi.Pointer<ffi.Pointer<ffi.Void>> out_texture_handle,
    ffi.Pointer<ffi.Int32> out_width,
    ffi.Pointer<ffi.Int32> out_height,
  ) {
    return Error.fromValue(
      _canvas_render_gpu(canvas, out_texture_handle, out_width, out_height),
    );
  }

  late final _canvas_render_gpuPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Pointer<ffi.Pointer<ffi.Void>>,
        ffi.Pointer<ffi.Int32>,
        ffi.Pointer<ffi.Int32>,
      )
    >
  >('gopost_canvas_render_gpu');
  late final _canvas_render_gpu =
      _canvas_render_gpuPtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
              ffi.Pointer<ffi.Int32>,
              ffi.Pointer<ffi.Int32>,
            )
          >();

  Error canvas_set_viewport(
    ffi.Pointer<Canvas> canvas,
    double pan_x,
    double pan_y,
    double zoom,
    double rotation,
  ) {
    return Error.fromValue(
      _canvas_set_viewport(canvas, pan_x, pan_y, zoom, rotation),
    );
  }

  late final _canvas_set_viewportPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Float,
        ffi.Float,
        ffi.Float,
        ffi.Float,
      )
    >
  >('gopost_canvas_set_viewport');
  late final _canvas_set_viewport =
      _canvas_set_viewportPtr
          .asFunction<
            int Function(ffi.Pointer<Canvas>, double, double, double, double)
          >();

  Error canvas_get_viewport(
    ffi.Pointer<Canvas> canvas,
    ffi.Pointer<ffi.Float> out_pan_x,
    ffi.Pointer<ffi.Float> out_pan_y,
    ffi.Pointer<ffi.Float> out_zoom,
    ffi.Pointer<ffi.Float> out_rotation,
  ) {
    return Error.fromValue(
      _canvas_get_viewport(
        canvas,
        out_pan_x,
        out_pan_y,
        out_zoom,
        out_rotation,
      ),
    );
  }

  late final _canvas_get_viewportPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        ffi.Pointer<ffi.Float>,
        ffi.Pointer<ffi.Float>,
        ffi.Pointer<ffi.Float>,
        ffi.Pointer<ffi.Float>,
      )
    >
  >('gopost_canvas_get_viewport');
  late final _canvas_get_viewport =
      _canvas_get_viewportPtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
            )
          >();

  /// --- Tile configuration (S5-06) ---
  Error canvas_set_tile_size(ffi.Pointer<Canvas> canvas, int tile_size) {
    return Error.fromValue(_canvas_set_tile_size(canvas, tile_size));
  }

  late final _canvas_set_tile_sizePtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<Canvas>, ffi.Int32)>
  >('gopost_canvas_set_tile_size');
  late final _canvas_set_tile_size =
      _canvas_set_tile_sizePtr
          .asFunction<int Function(ffi.Pointer<Canvas>, int)>();

  Error canvas_get_dirty_tile_count(
    ffi.Pointer<Canvas> canvas,
    ffi.Pointer<ffi.Int32> out_count,
  ) {
    return Error.fromValue(_canvas_get_dirty_tile_count(canvas, out_count));
  }

  late final _canvas_get_dirty_tile_countPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<Canvas>, ffi.Pointer<ffi.Int32>)
    >
  >('gopost_canvas_get_dirty_tile_count');
  late final _canvas_get_dirty_tile_count =
      _canvas_get_dirty_tile_countPtr
          .asFunction<
            int Function(ffi.Pointer<Canvas>, ffi.Pointer<ffi.Int32>)
          >();

  Error canvas_set_frame_callback(
    ffi.Pointer<Canvas> canvas,
    GopostFrameCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return Error.fromValue(
      _canvas_set_frame_callback(canvas, callback, user_data),
    );
  }

  late final _canvas_set_frame_callbackPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<Canvas>,
        GopostFrameCallback,
        ffi.Pointer<ffi.Void>,
      )
    >
  >('gopost_canvas_set_frame_callback');
  late final _canvas_set_frame_callback =
      _canvas_set_frame_callbackPtr
          .asFunction<
            int Function(
              ffi.Pointer<Canvas>,
              GopostFrameCallback,
              ffi.Pointer<ffi.Void>,
            )
          >();
}

final class Engine extends ffi.Opaque {}

final class EngineConfig extends ffi.Struct {
  @ffi.Uint32()
  external int thread_count;

  @ffi.Size()
  external int frame_pool_size_mb;

  @ffi.Int()
  external int enable_gpu;

  /// 0=error, 1=warn, 2=info, 3=debug
  @ffi.Int()
  external int log_level;
}

enum Error {
  GOPOST_OK(0),
  GOPOST_ERROR_INVALID_ARGUMENT(-1),
  GOPOST_ERROR_OUT_OF_MEMORY(-2),
  GOPOST_ERROR_NOT_INITIALIZED(-3),
  GOPOST_ERROR_ALREADY_INITIALIZED(-4),
  GOPOST_ERROR_GPU_NOT_AVAILABLE(-5),
  GOPOST_ERROR_CODEC_NOT_FOUND(-6),
  GOPOST_ERROR_IO(-7),
  GOPOST_ERROR_CRYPTO(-8),
  GOPOST_ERROR_UNKNOWN(-99);

  final int value;
  const Error(this.value);

  static Error fromValue(int value) => switch (value) {
    0 => GOPOST_OK,
    -1 => GOPOST_ERROR_INVALID_ARGUMENT,
    -2 => GOPOST_ERROR_OUT_OF_MEMORY,
    -3 => GOPOST_ERROR_NOT_INITIALIZED,
    -4 => GOPOST_ERROR_ALREADY_INITIALIZED,
    -5 => GOPOST_ERROR_GPU_NOT_AVAILABLE,
    -6 => GOPOST_ERROR_CODEC_NOT_FOUND,
    -7 => GOPOST_ERROR_IO,
    -8 => GOPOST_ERROR_CRYPTO,
    -99 => GOPOST_ERROR_UNKNOWN,
    _ => throw ArgumentError('Unknown value for Error: $value'),
  };
}

enum PixelFormat {
  GOPOST_PIXEL_FORMAT_RGBA8(0),
  GOPOST_PIXEL_FORMAT_BGRA8(1),
  GOPOST_PIXEL_FORMAT_NV12(2),
  GOPOST_PIXEL_FORMAT_YUV420P(3);

  final int value;
  const PixelFormat(this.value);

  static PixelFormat fromValue(int value) => switch (value) {
    0 => GOPOST_PIXEL_FORMAT_RGBA8,
    1 => GOPOST_PIXEL_FORMAT_BGRA8,
    2 => GOPOST_PIXEL_FORMAT_NV12,
    3 => GOPOST_PIXEL_FORMAT_YUV420P,
    _ => throw ArgumentError('Unknown value for PixelFormat: $value'),
  };
}

final class Frame extends ffi.Struct {
  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.UnsignedInt()
  external int formatAsInt;

  PixelFormat get format => PixelFormat.fromValue(formatAsInt);

  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int data_size;

  @ffi.Size()
  external int stride;
}

final class Rect extends ffi.Struct {
  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double width;

  @ffi.Float()
  external double height;
}

final class Color extends ffi.Struct {
  @ffi.Float()
  external double r;

  @ffi.Float()
  external double g;

  @ffi.Float()
  external double b;

  @ffi.Float()
  external double a;
}

final class CryptoContext extends ffi.Opaque {}

enum GpuBackend {
  GOPOST_GPU_BACKEND_NONE(0),
  GOPOST_GPU_BACKEND_METAL(1),
  GOPOST_GPU_BACKEND_VULKAN(2),
  GOPOST_GPU_BACKEND_GLES(3),
  GOPOST_GPU_BACKEND_WEBGL(4);

  final int value;
  const GpuBackend(this.value);

  static GpuBackend fromValue(int value) => switch (value) {
    0 => GOPOST_GPU_BACKEND_NONE,
    1 => GOPOST_GPU_BACKEND_METAL,
    2 => GOPOST_GPU_BACKEND_VULKAN,
    3 => GOPOST_GPU_BACKEND_GLES,
    4 => GOPOST_GPU_BACKEND_WEBGL,
    _ => throw ArgumentError('Unknown value for GpuBackend: $value'),
  };
}

final class GpuContext extends ffi.Opaque {}

final class Texture extends ffi.Opaque {}

final class Pipeline extends ffi.Opaque {}

final class Template extends ffi.Opaque {}

enum TemplateType {
  GOPOST_TEMPLATE_TYPE_VIDEO(1),
  GOPOST_TEMPLATE_TYPE_IMAGE(2);

  final int value;
  const TemplateType(this.value);

  static TemplateType fromValue(int value) => switch (value) {
    1 => GOPOST_TEMPLATE_TYPE_VIDEO,
    2 => GOPOST_TEMPLATE_TYPE_IMAGE,
    _ => throw ArgumentError('Unknown value for TemplateType: $value'),
  };
}

enum SectionType {
  GOPOST_SECTION_METADATA(0),
  GOPOST_SECTION_LAYERS(1),
  GOPOST_SECTION_ASSETS(2),
  GOPOST_SECTION_RENDER(3),
  GOPOST_SECTION_BLOB(4);

  final int value;
  const SectionType(this.value);

  static SectionType fromValue(int value) => switch (value) {
    0 => GOPOST_SECTION_METADATA,
    1 => GOPOST_SECTION_LAYERS,
    2 => GOPOST_SECTION_ASSETS,
    3 => GOPOST_SECTION_RENDER,
    4 => GOPOST_SECTION_BLOB,
    _ => throw ArgumentError('Unknown value for SectionType: $value'),
  };
}

enum ImageFormat {
  GOPOST_IMAGE_FORMAT_UNKNOWN(0),
  GOPOST_IMAGE_FORMAT_JPEG(1),
  GOPOST_IMAGE_FORMAT_PNG(2),
  GOPOST_IMAGE_FORMAT_WEBP(3),
  GOPOST_IMAGE_FORMAT_HEIC(4);

  final int value;
  const ImageFormat(this.value);

  static ImageFormat fromValue(int value) => switch (value) {
    0 => GOPOST_IMAGE_FORMAT_UNKNOWN,
    1 => GOPOST_IMAGE_FORMAT_JPEG,
    2 => GOPOST_IMAGE_FORMAT_PNG,
    3 => GOPOST_IMAGE_FORMAT_WEBP,
    4 => GOPOST_IMAGE_FORMAT_HEIC,
    _ => throw ArgumentError('Unknown value for ImageFormat: $value'),
  };
}

enum ExifOrientation {
  GOPOST_ORIENTATION_NORMAL(1),
  GOPOST_ORIENTATION_FLIP_H(2),
  GOPOST_ORIENTATION_ROTATE_180(3),
  GOPOST_ORIENTATION_FLIP_V(4),
  GOPOST_ORIENTATION_TRANSPOSE(5),
  GOPOST_ORIENTATION_ROTATE_90(6),
  GOPOST_ORIENTATION_TRANSVERSE(7),
  GOPOST_ORIENTATION_ROTATE_270(8);

  final int value;
  const ExifOrientation(this.value);

  static ExifOrientation fromValue(int value) => switch (value) {
    1 => GOPOST_ORIENTATION_NORMAL,
    2 => GOPOST_ORIENTATION_FLIP_H,
    3 => GOPOST_ORIENTATION_ROTATE_180,
    4 => GOPOST_ORIENTATION_FLIP_V,
    5 => GOPOST_ORIENTATION_TRANSPOSE,
    6 => GOPOST_ORIENTATION_ROTATE_90,
    7 => GOPOST_ORIENTATION_TRANSVERSE,
    8 => GOPOST_ORIENTATION_ROTATE_270,
    _ => throw ArgumentError('Unknown value for ExifOrientation: $value'),
  };
}

final class ImageInfo extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int channels;

  @ffi.UnsignedInt()
  external int formatAsInt;

  ImageFormat get format => ImageFormat.fromValue(formatAsInt);

  @ffi.UnsignedInt()
  external int orientationAsInt;

  ExifOrientation get orientation =>
      ExifOrientation.fromValue(orientationAsInt);

  @ffi.Int32()
  external int has_alpha;

  /// 0=sRGB, 1=DisplayP3, 2=AdobeRGB
  @ffi.Int32()
  external int color_space;
}

/// --- Encoder (S5-02) ---
final class JpegEncodeOpts extends ffi.Struct {
  /// 1-100, default 85
  @ffi.Int32()
  external int quality;

  /// 0 or 1
  @ffi.Int32()
  external int progressive;
}

final class PngEncodeOpts extends ffi.Struct {
  /// 0-9, default 6
  @ffi.Int32()
  external int compression_level;
}

final class WebpEncodeOpts extends ffi.Struct {
  /// 1-100, default 80
  @ffi.Int32()
  external int quality;

  /// 0 or 1
  @ffi.Int32()
  external int lossless;
}

final class Canvas extends ffi.Opaque {}

/// --- Enums ---
enum LayerType {
  GOPOST_LAYER_IMAGE(0),
  GOPOST_LAYER_SOLID_COLOR(1),
  GOPOST_LAYER_TEXT(2),
  GOPOST_LAYER_SHAPE(3),
  GOPOST_LAYER_GROUP(4),
  GOPOST_LAYER_ADJUSTMENT(5),
  GOPOST_LAYER_GRADIENT(6),
  GOPOST_LAYER_STICKER(7);

  final int value;
  const LayerType(this.value);

  static LayerType fromValue(int value) => switch (value) {
    0 => GOPOST_LAYER_IMAGE,
    1 => GOPOST_LAYER_SOLID_COLOR,
    2 => GOPOST_LAYER_TEXT,
    3 => GOPOST_LAYER_SHAPE,
    4 => GOPOST_LAYER_GROUP,
    5 => GOPOST_LAYER_ADJUSTMENT,
    6 => GOPOST_LAYER_GRADIENT,
    7 => GOPOST_LAYER_STICKER,
    _ => throw ArgumentError('Unknown value for LayerType: $value'),
  };
}

enum BlendMode {
  GOPOST_BLEND_NORMAL(0),
  GOPOST_BLEND_MULTIPLY(1),
  GOPOST_BLEND_SCREEN(2),
  GOPOST_BLEND_OVERLAY(3);

  final int value;
  const BlendMode(this.value);

  static BlendMode fromValue(int value) => switch (value) {
    0 => GOPOST_BLEND_NORMAL,
    1 => GOPOST_BLEND_MULTIPLY,
    2 => GOPOST_BLEND_SCREEN,
    3 => GOPOST_BLEND_OVERLAY,
    _ => throw ArgumentError('Unknown value for BlendMode: $value'),
  };
}

enum ColorSpace {
  GOPOST_COLOR_SPACE_SRGB(0),
  GOPOST_COLOR_SPACE_DISPLAY_P3(1),
  GOPOST_COLOR_SPACE_ADOBE_RGB(2);

  final int value;
  const ColorSpace(this.value);

  static ColorSpace fromValue(int value) => switch (value) {
    0 => GOPOST_COLOR_SPACE_SRGB,
    1 => GOPOST_COLOR_SPACE_DISPLAY_P3,
    2 => GOPOST_COLOR_SPACE_ADOBE_RGB,
    _ => throw ArgumentError('Unknown value for ColorSpace: $value'),
  };
}

/// --- Canvas config ---
final class CanvasConfig extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Float()
  external double dpi;

  @ffi.UnsignedInt()
  external int color_spaceAsInt;

  ColorSpace get color_space => ColorSpace.fromValue(color_spaceAsInt);

  @ffi.Float()
  external double bg_r;

  @ffi.Float()
  external double bg_g;

  @ffi.Float()
  external double bg_b;

  @ffi.Float()
  external double bg_a;

  @ffi.Int32()
  external int transparent_bg;
}

/// --- Layer info (read-only query result) ---
final class LayerInfo extends ffi.Struct {
  @ffi.Int32()
  external int id;

  @ffi.UnsignedInt()
  external int typeAsInt;

  LayerType get type => LayerType.fromValue(typeAsInt);

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> name;

  @ffi.Float()
  external double opacity;

  @ffi.UnsignedInt()
  external int blend_modeAsInt;

  BlendMode get blend_mode => BlendMode.fromValue(blend_modeAsInt);

  @ffi.Int32()
  external int visible;

  @ffi.Int32()
  external int locked;

  /// translation
  @ffi.Float()
  external double tx;

  @ffi.Float()
  external double ty;

  /// scale
  @ffi.Float()
  external double sx;

  @ffi.Float()
  external double sy;

  /// degrees
  @ffi.Float()
  external double rotation;

  /// layer content pixel width
  @ffi.Int32()
  external int content_w;

  /// layer content pixel height
  @ffi.Int32()
  external int content_h;
}

typedef GopostFrameCallbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<ffi.Void> texture_handle,
      ffi.Int32 width,
      ffi.Int32 height,
    );
typedef DartGopostFrameCallbackFunction =
    void Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<ffi.Void> texture_handle,
      int width,
      int height,
    );

/// --- Frame callback for continuous rendering ---
typedef GopostFrameCallback =
    ffi.Pointer<ffi.NativeFunction<GopostFrameCallbackFunction>>;

const String GOPOST_MAGIC_BYTES = 'GOPT';

const int GOPOST_MAGIC_SIZE = 4;

const int GOPOST_FILE_HEADER_SIZE = 16;

const int GOPOST_ENCRYPTION_HEADER_SIZE = 64;
